# Generated by Django 2.0.7 on 2018-07-21 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='pic',
            fields=[
                ('name', models.CharField(default='', max_length=200)),
                ('url', models.TextField(default='', primary_key=True, serialize=False)),
                ('gender', models.CharField(default='M', max_length=1)),
                ('colors', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='findColor.color')),
            ],
        ),
    ]
