# Generated by Django 2.0.7 on 2018-07-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findColor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possibleColor', models.TextField()),
                ('photo', models.ImageField(upload_to='user')),
            ],
        ),
    ]
